### ISSUE TITLE
Upgrade to Angular13 fails

### ISSUE THREAD

**Issue by damogallagher** [merlosy/ngx-material-file-input#92]
When I upgraded to Angular 13 this morning - I started receiving this error

```
Error: node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts:9:22 - error TS2720: Class 'FileInputComponent' incorrectly implements class 'MatFormFieldControl<FileInput>'. Did you mean to extend 'MatFormFieldControl<FileInput>' and inherit its members as a subclass?
  Type 'FileInputComponent' is missing the following properties from type 'MatFormFieldControl<FileInput>': stateChanges, errorState

9 export declare class FileInputComponent extends FileInputMixinBase implements MatFormFieldControl<FileInput>, ControlValueAccessor, OnInit, OnDestroy, DoCheck {
```

Would it be possible to get this issue fixed within the library?

**Comment by mcaden** [comment]
I've looked into this some - it appears the main problem is that `FileInputMixinBase` uses type `CanUpdateErrorStateCtor` - but in NG 13 that type is no longer exported.

See commit: https://github.com/angular/components/commit/7bc9bfb9dc233256f6e7063c62e4371a5a1da346#diff-606a332883a0dda9b5ef3fa3473ab14ab59820c71ae2b04f801ec4d1d4e0ccb4

It was deprecated with the following:

```ts
/**
 * @docs-private
 * @deprecated No longer necessary to apply to mixin classes. To be made private.
 * @breaking-change 13.0.0
 */```

and then `export` was removed. I'm not sure why it's no longer necessary to mixin.

I created a branch, updated it to angular 13 in order to repro the problem, found this, and then as a hack copy/pasted `type CanUpdateErrorStateCtor = Constructor<CanUpdateErrorState> & AbstractConstructor<CanUpdateErrorState>;`  into the local file. I've tested locally both via the unit tests and by copying dist into my project and it works.

I can PR it but it feels like a hacky workaround. I feel like the solution instead should be using whatever the Angular team intended the mixin to be replaced by but I haven't found dialog explaining what should be done instead.

If there's demand I'll PR what I've got though or if somebody can enlighten me on what I'm missing I'll gladly fix that before I PR.

**Comment by mcaden** [comment]
I looked into their commits leading up to the deprecation and it looks like they basically just relaxed some of the type specifications and removed a bunch of the boilerplate. I did the same and created PR bringing everything up to 13. I haven't really worked with nx/nrwl but I think I got it right.

**Comment by damogallagher** [comment]
Had a quick review of your pr @mcaden  and it looks good.
Would be great if @merlosy could review and merge as this is blocked our upgrade to Angular 13

**Comment by damogallagher** [comment]
@mcaden could you by any chance create a fork of this repository with your fixes and push to npmjs.org?

**Comment by mcaden** [comment]
I can... it feels a bit like hijacking so I don't think it's my first choice. I'm not entirely sure the etiquette on this?

What I've done in the meantime that is working for me is that my consuming project is using yarn 2 with [zero-installs](https://yarnpkg.com/features/zero-installs)

1. build my fork
2. use `yarn pack` in the built directory (dist\material-file-input)
3. copy the resulting file to my consuming project
4. remove reference to `ngx-material-file-input`
5. `yarn add ./<packed filename>`
6. delete packed file

The packed file is copied into the `.yarn/cache` folder and gets committed (which is why yarn 2 with zero-installs is a requirement for this approach).

I don't like it but it packages up my changes without stepping on toes.

I respect the maintainer for this project and appreciate the work done. I also respect he may be super-busy at the moment and this project is a lower priority. Hopefully somebody with write-privileges will be able to approve the PR (or suggest where I might improve it so it can be approved).

Before I publish a fork I want to verify whether the project is abandoned.

**Comment by nbonneau** [comment]
Hello, we would need this fix for our Angular 13 migration as well, could you tell us when this will be fixed?

**Comment by damogallagher** [comment]
Hi

I can verify this issue is now resolved

Thanks
Damien

**Comment by mcaden** [comment]
@damogallagher Did something get missed? Why reopen?

**Comment by jordankkk** [comment]
On angular v13.1 error

```
Error: node_modules/ngx-material-file-input/lib/file-input/file-input-mixin.d.ts:2:10 - error TS2305: Module '"@angular/material/core"' has no exported member 'CanUpdateErrorStateCtor'.

2 import { CanUpdateErrorStateCtor, ErrorStateMatcher } from '@angular/material/core';
```

```
Error: node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts:9:22 - error TS2720: Class 'FileInputComponent' incorrectly implements class 'MatFormFieldControl<FileInput>'. Did you mean to extend 'MatFormFieldControl<FileInput>' and inherit its members as a subclass?
  Type 'FileInputComponent' is missing the following properties from type 'MatFormFieldControl<FileInput>': stateChanges, errorState

9 export declare class FileInputComponent extends FileInputMixinBase implements MatFormFieldControl<FileInput>, ControlValueAccessor, OnInit, OnDestroy, DoCheck {
```

**Comment by mcaden** [comment]
@jordankkk That's the same issue I fixed in the PR above and merlosy released in version 3.0.0. I've just updated to angular 13.1 and I can verify that it still works fine. Are you using 3.0.0?

I'm not sure why this issue is still open. @damogallagher can you shed some light on this?

**Comment by damogallagher** [comment]
Apologies this issue can be closed. I will close now

**Comment by mcaden** [comment]
Thanks. I just wasn't sure if reopening meant I missed something or if it was an accident/mistake.
